version: 1.0.{build}-{branch}

image:
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 26-x64

install:
  - cmd: set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - sh: |
      if [ "$RUBY_VERSION" = "25-x64" ]
      then
          rvm use 2.5
      elif [ "$RUBY_VERSION" = "26-x64" ]
      then
          rvm use 2.6
      fi
  - sh: gem update --system --silent --no-document
  - sh: gem install bundler --silent --no-document
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec && bundle exec cucumber -f progress
